# Generated by Django 5.1.1 on 2024-09-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0003_orgcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=130),
            preserve_default=False,
        ),
    ]
