# Generated by Django 5.1.1 on 2024-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='', max_length=250, upload_to='org/'),
            preserve_default=False,
        ),
    ]
